ENV['OCTOKIT_API_ENDPOINT'] = 'https://example.com/api/v3'
ENV['OCTOKIT_WEB_ENDPOINT'] = 'https://example.com/'
ENV['GITHUB_OAUTH_DOMAIN'] = 'https://example.com'
ENV['GITHUB_CLIENT_ID'] = 'example_id'
ENV['GITHUB_CLIENT_SECRET'] = 'example_secret'
ENV['GITHUB_CLIENT_CALLBACK'] = 'http://example.com/flail'
